/**
 * TrailWatch Demo Data Layer
 * 
 * Represents two real pilot parks:
 *   - Royal National Park, NSW, Australia (Australia's oldest national park, est. 1879)
 *   - Olympic National Park, Washington, USA
 * 
 * All data is simulated but based on real park characteristics.
 * Replace with Supabase queries for production.
 */

export const PARKS = [
  {
    id: 'royal-np',
    name: 'Royal National Park',
    agency: 'NSW National Parks & Wildlife Service',
    country: 'AU',
    state_region: 'New South Wales',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    totalTrails: 31,
    totalParkingSpaces: 540,
    description: "Australia's oldest national park, established 1879. 16,000 hectares of coastal heath, rainforest, and sandstone gorges south of Sydney.",
    timezone: 'Australia/Sydney',
    coordinates: { lat: -34.0850, lng: 151.0520 },
    total_area_ha: 16000,
    established_year: 1879,
    emergency_contact: '1300 361 967',
    is_active: true,
  },
  {
    id: 'olympic-np',
    name: 'Olympic National Park',
    agency: 'US National Park Service',
    country: 'US',
    state_region: 'Washington',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
    totalTrails: 48,
    totalParkingSpaces: 820,
    description: "UNESCO World Heritage Site. Three distinct ecosystems — glacier-capped mountains, old-growth rainforest, and 70 miles of wilderness coast on Washington's Olympic Peninsula.",
    timezone: 'America/Los_Angeles',
    coordinates: { lat: 47.8021, lng: -123.6044 },
    total_area_ha: 373397,
    established_year: 1938,
    emergency_contact: '360-565-3130',
    is_active: true,
  },
  {
    id: 'demo-park',
    name: 'Blue Ridge State Reserve',
    agency: 'Parks Victoria',
    country: 'AU',
    state_region: 'Victoria',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    totalTrails: 18,
    totalParkingSpaces: 280,
    description: 'High-altitude reserve protecting ancient snowgum woodlands, alpine bogs, and dramatic basalt formations across 8,200 hectares.',
    timezone: 'Australia/Melbourne',
    coordinates: { lat: -36.9500, lng: 146.4200 },
    total_area_ha: 8200,
    established_year: 1956,
    emergency_contact: '13 19 63',
    is_active: true,
  },
]

export const PARKING_LOTS = [
  // Royal National Park
  { id: 'rnp-audley',      parkId: 'royal-np',   name: 'Audley Weir Car Park',         total: 180, occupied: 134, status: 'busy',   sensor_id: 'rnp-sensor-01', last_sensor_ping: new Date().toISOString() },
  { id: 'rnp-wattamolla',  parkId: 'royal-np',   name: 'Wattamolla Beach Car Park',     total: 120, occupied: 120, status: 'full',   sensor_id: 'rnp-sensor-02', last_sensor_ping: new Date().toISOString() },
  { id: 'rnp-bundeena',    parkId: 'royal-np',   name: 'Bundeena Drive Trailhead',      total: 60,  occupied: 22,  status: 'open',   sensor_id: 'rnp-sensor-03', last_sensor_ping: new Date().toISOString() },
  { id: 'rnp-visitor',     parkId: 'royal-np',   name: 'Visitor Centre (Sutherland)',   total: 90,  occupied: 41,  status: 'open',   sensor_id: 'rnp-sensor-04', last_sensor_ping: new Date().toISOString() },
  { id: 'rnp-garie',       parkId: 'royal-np',   name: 'Garie Beach Car Park',          total: 90,  occupied: 83,  status: 'busy',   sensor_id: 'rnp-sensor-05', last_sensor_ping: new Date().toISOString() },
  // Olympic National Park
  { id: 'onp-hoh',         parkId: 'olympic-np', name: 'Hoh Rain Forest Visitor Center',total: 200, occupied: 168, status: 'busy',   sensor_id: 'onp-sensor-01', last_sensor_ping: new Date().toISOString() },
  { id: 'onp-hurricane',   parkId: 'olympic-np', name: 'Hurricane Ridge Day Lodge',     total: 250, occupied: 250, status: 'full',   sensor_id: 'onp-sensor-02', last_sensor_ping: new Date().toISOString() },
  { id: 'onp-sol-duc',     parkId: 'olympic-np', name: 'Sol Duc Trailhead',             total: 120, occupied: 55,  status: 'open',   sensor_id: 'onp-sensor-03', last_sensor_ping: new Date().toISOString() },
  { id: 'onp-quinault',    parkId: 'olympic-np', name: 'Lake Quinault South Shore',     total: 80,  occupied: 12,  status: 'open',   sensor_id: 'onp-sensor-04', last_sensor_ping: new Date().toISOString() },
  { id: 'onp-rialto',      parkId: 'olympic-np', name: 'Rialto Beach Parking Area',     total: 170, occupied: 149, status: 'busy',   sensor_id: 'onp-sensor-05', last_sensor_ping: new Date().toISOString() },
  // Blue Ridge
  { id: 'br-summit',       parkId: 'demo-park',  name: 'Summit Road Car Park',          total: 80,  occupied: 71,  status: 'busy',   sensor_id: null, last_sensor_ping: null },
  { id: 'br-falls',        parkId: 'demo-park',  name: 'Cascades Falls Trailhead',      total: 60,  occupied: 14,  status: 'open',   sensor_id: null, last_sensor_ping: null },
  { id: 'br-village',      parkId: 'demo-park',  name: 'Mount Beauty Village Lot',      total: 140, occupied: 138, status: 'full',   sensor_id: null, last_sensor_ping: null },
]

export const TRAILS = [
  // Royal National Park
  {
    id: 'rnp-coastal',   parkId: 'royal-np',
    name: 'Coast Track',
    difficulty: 'Moderate',
    length: 26.0, length_unit: 'km',
    elevationGain: 640,
    currentHikers: 89,
    maxCapacity: 150,
    estimatedTime: '2–3 days',
    status: 'open',
    crowdLevel: 'busy',
    description: "Australia's most iconic multi-day coastal walk. Clifftop heathland, pristine beaches, and waterfalls from Bundeena to Otford.",
    features: ['Coastal Views', 'Swimming Holes', 'Multi-day', 'Backcountry Camping'],
    is_accessible: false,
  },
  {
    id: 'rnp-wattamolla', parkId: 'royal-np',
    name: 'Wattamolla to Curracurrong Falls',
    difficulty: 'Easy',
    length: 5.5, length_unit: 'km',
    elevationGain: 95,
    currentHikers: 143,
    maxCapacity: 160,
    estimatedTime: '1.5–2 hrs',
    status: 'open',
    crowdLevel: 'very_busy',
    description: 'Coastal heathland walk to a stunning lagoon and clifftop waterfall. Extremely popular on weekends — arrive before 8am.',
    features: ['Waterfall', 'Lagoon Swimming', 'Ocean Views', 'Family Friendly'],
    is_accessible: false,
  },
  {
    id: 'rnp-forest',    parkId: 'royal-np',
    name: 'Karloo Walking Track',
    difficulty: 'Moderate',
    length: 10.0, length_unit: 'km',
    elevationGain: 280,
    currentHikers: 27,
    maxCapacity: 80,
    estimatedTime: '3–4 hrs',
    status: 'open',
    crowdLevel: 'moderate',
    description: 'Through ancient casuarina forest and sandstone gorges to the crystal pools at the base of Karloo waterfall.',
    features: ['Waterfall', 'Sandstone Gorge', 'Rock Pools', 'Birdwatching'],
    is_accessible: false,
  },
  {
    id: 'rnp-jibbon',    parkId: 'royal-np',
    name: 'Jibbon Aboriginal Engravings Track',
    difficulty: 'Easy',
    length: 3.0, length_unit: 'km',
    elevationGain: 40,
    currentHikers: 18,
    maxCapacity: 50,
    estimatedTime: '1 hr',
    status: 'open',
    crowdLevel: 'quiet',
    description: 'Cultural heritage walk to 2,000-year-old Aboriginal rock engravings at Jibbon Point overlooking Port Hacking.',
    features: ['Cultural Heritage', 'Ocean Views', 'Rock Engravings', 'Accessible Path'],
    is_accessible: true,
  },
  {
    id: 'rnp-palm',      parkId: 'royal-np',
    name: 'Palm Jungle Loop',
    difficulty: 'Easy',
    length: 2.0, length_unit: 'km',
    elevationGain: 20,
    currentHikers: 0,
    maxCapacity: 60,
    estimatedTime: '45 min',
    status: 'closed',
    crowdLevel: 'quiet',
    description: 'Temporarily closed — storm damage to boardwalk section. Expected reopening 3 weeks.',
    features: ['Rainforest', 'Cabbage Tree Palms', 'Boardwalk'],
    is_accessible: true,
  },
  // Olympic National Park
  {
    id: 'onp-hoh-rain',  parkId: 'olympic-np',
    name: 'Hoh River Trail',
    difficulty: 'Easy',
    length: 29.0, length_unit: 'km',
    elevationGain: 370,
    currentHikers: 61,
    maxCapacity: 120,
    estimatedTime: '2–4 days',
    status: 'open',
    crowdLevel: 'moderate',
    description: 'Walk through one of the largest temperate rainforests in the US. Moss-draped maples, towering Sitka spruce, and glacier views of Mount Olympus.',
    features: ['Temperate Rainforest', 'Glacier Views', 'Backcountry', 'Elk Viewing'],
    is_accessible: false,
  },
  {
    id: 'onp-hurricane', parkId: 'olympic-np',
    name: 'Hurricane Hill Trail',
    difficulty: 'Moderate',
    length: 5.0, length_unit: 'km',
    elevationGain: 436,
    currentHikers: 112,
    maxCapacity: 130,
    estimatedTime: '2–3 hrs',
    status: 'open',
    crowdLevel: 'busy',
    description: 'Alpine meadow walk to panoramic views of the Strait of Juan de Fuca, Vancouver Island, and the Olympic Mountains.',
    features: ['Alpine Meadows', 'Panoramic Views', 'Wildflowers', 'Wildlife'],
    is_accessible: false,
  },
  {
    id: 'onp-sol-duc',   parkId: 'olympic-np',
    name: 'Sol Duc Falls Trail',
    difficulty: 'Easy',
    length: 2.6, length_unit: 'km',
    elevationGain: 55,
    currentHikers: 44,
    maxCapacity: 100,
    estimatedTime: '45 min–1 hr',
    status: 'open',
    crowdLevel: 'moderate',
    description: 'Short walk through old-growth Douglas fir and cedar to one of the most photographed waterfalls in the Olympic Peninsula.',
    features: ['Waterfall', 'Old-growth Forest', 'Accessible Section', 'Photography'],
    is_accessible: true,
  },
  {
    id: 'onp-rialto',    parkId: 'olympic-np',
    name: 'Rialto Beach to Chilean Memorial',
    difficulty: 'Easy',
    length: 5.6, length_unit: 'km',
    elevationGain: 15,
    currentHikers: 78,
    maxCapacity: 120,
    estimatedTime: '2–3 hrs',
    status: 'open',
    crowdLevel: 'busy',
    description: 'Wild Pacific coastline walk past sea stacks, tide pools, and driftwood forests to the historic Chilean Memorial shipwreck site.',
    features: ['Sea Stacks', 'Tide Pools', 'Wilderness Coast', 'Historic Site'],
    is_accessible: false,
  },
  // Blue Ridge
  {
    id: 'br-summit',     parkId: 'demo-park',
    name: 'Summit Ridge Circuit',
    difficulty: 'Hard',
    length: 14.0, length_unit: 'km',
    elevationGain: 820,
    currentHikers: 23,
    maxCapacity: 50,
    estimatedTime: '5–7 hrs',
    status: 'open',
    crowdLevel: 'moderate',
    description: 'Challenging alpine circuit through snowgum woodland and exposed basalt ridgelines with 360° views to the Murray Plains.',
    features: ['Alpine Flora', 'Summit Views', 'Snowgums', 'Exposed Ridgeline'],
    is_accessible: false,
  },
  {
    id: 'br-falls',      parkId: 'demo-park',
    name: 'Cascades Falls Walk',
    difficulty: 'Easy',
    length: 3.2, length_unit: 'km',
    elevationGain: 110,
    currentHikers: 8,
    maxCapacity: 60,
    estimatedTime: '1–1.5 hrs',
    status: 'open',
    crowdLevel: 'quiet',
    description: 'Gentle walk along a fern-lined creek to three tiered waterfalls in a sheltered basalt gorge.',
    features: ['Waterfall', 'Ferns', 'Creek Walk', 'Family Friendly'],
    is_accessible: false,
  },
]

export const HOURLY_DATA = [
  { hour: '6am',  hikers: 8,   parking: 12  },
  { hour: '7am',  hikers: 28,  parking: 38  },
  { hour: '8am',  hikers: 67,  parking: 82  },
  { hour: '9am',  hikers: 118, parking: 138 },
  { hour: '10am', hikers: 192, parking: 218 },
  { hour: '11am', hikers: 241, parking: 274 },
  { hour: '12pm', hikers: 258, parking: 291 },
  { hour: '1pm',  hikers: 249, parking: 278 },
  { hour: '2pm',  hikers: 214, parking: 242 },
  { hour: '3pm',  hikers: 171, parking: 193 },
  { hour: '4pm',  hikers: 128, parking: 147 },
  { hour: '5pm',  hikers: 79,  parking: 91  },
  { hour: '6pm',  hikers: 31,  parking: 44  },
]

export const WEEKLY_DATA = [
  { day: 'Mon', hikers: 298,  parking: 68  },
  { day: 'Tue', hikers: 271,  parking: 62  },
  { day: 'Wed', hikers: 318,  parking: 73  },
  { day: 'Thu', hikers: 284,  parking: 66  },
  { day: 'Fri', hikers: 487,  parking: 118 },
  { day: 'Sat', hikers: 812,  parking: 198 },
  { day: 'Sun', hikers: 743,  parking: 181 },
]

// Simulated live sensor tick — call this to get slightly varied data
export function simulateSensorTick(lots: typeof PARKING_LOTS) {
  return lots.map(lot => {
    const delta = Math.floor(Math.random() * 5) - 2
    const newOccupied = Math.max(0, Math.min(lot.total, lot.occupied + delta))
    const pct = newOccupied / lot.total
    const status = newOccupied >= lot.total ? 'full' : pct > 0.8 ? 'busy' : 'open'
    return { ...lot, occupied: newOccupied, status }
  })
}
